### ISSUE TITLE
Copied skid from me

### ISSUE THREAD

**Issue by TajuModding** [MrVenomYT/ticket-tool#3]
https://github.com/TajuModding/Discord-Button-Tickets-Bot

**Comment by MrVenomYT** [comment]
I nvr say that i created it lol

**Comment by TajuModding** [comment]
![Capture](https://user-images.githubusercontent.com/73745640/151556771-768b3206-7452-4749-a1e8-fd32b8b32de3.PNG)

**Comment by MrVenomYT** [comment]
Lol console doesnt matter 😑😑 why are you annoying

**Comment by TajuModding** [comment]
delete this repo
